version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend-user-1:
    build: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    depends_on:
      - server

  frontend-user-2:
    build: ./client
    ports:
      - "3002:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    

